[[pages]]
path = "vista/01_introduccion.py"
name = "INTRODUCCION"
icon = "ğŸ "

[[pages]]
path = "vista/02_obtener_series_inegi.py"
name = "INEGI"
icon = "ğŸ“—"

[[pages]]
path = "vista/03_obtener_series_banxico.py"
name = "BANXICO"
icon = "ğŸ“˜"

[[pages]]
path = "vista/04_obtener_series_inegi_y_banxico.py"
name = "INEGI Y BANXICO"
icon = "ğŸ“™"

[[pages]]
path = "vista/05_comparacion.py"
name = "Comparacion de datos"
icon = "ğŸ†š"

[[pages]]
path = "vista/04_buscar.py"
name = "BUSCAR RUTAS"
icon = "ğŸ”"
